IF (EXISTS (SELECT * 
                 FROM [INFORMATION_SCHEMA].[TABLES] 
                 WHERE [TABLE_SCHEMA] = 'MTE'
				 AND [TABLE_NAME] = 'Testimonial'))
BEGIN
    INSERT INTO [MTE].[Testimonial] ([ClientName], [ClientProfession], [Review], [ClientPhotoUrl], [CreatedDate], [ModifiedDate]) VALUES ('Vino', 'Wilderness Explorer ', 'As a passionate wilderness explorer, Mini Traveling Explorer has been an invaluable resource for planning my outdoor adventures. From remote camping spots to scenic hiking trails, this platform provides comprehensive guidance for exploring the great outdoors. Thanks to Mini Traveling Explorer, I''ve discovered hidden wilderness gems and embarked on unforgettable journeys into nature.', 'https://i.ibb.co/6bXzhws/Vino.jpg', GETUTCDATE(), GETUTCDATE());
    INSERT INTO [MTE].[Testimonial] ([ClientName], [ClientProfession], [Review], [ClientPhotoUrl], [CreatedDate], [ModifiedDate]) VALUES ('Emily Watson', 'Travel Enthusiast', 'As an avid traveler, I''ve visited countless websites, but Mini Traveling Explorer stands out for its user-friendly interface and comprehensive features. It''s become my go-to platform for planning seamless and unforgettable trips.', 'https://i.ibb.co/Hnqrtxc/Emily.jpg', GETUTCDATE(), GETUTCDATE());
    INSERT INTO [MTE].[Testimonial] ([ClientName], [ClientProfession], [Review], [ClientPhotoUrl], [CreatedDate], [ModifiedDate]) VALUES ('John Smith', 'Business Executive', 'Mini Traveling Explorer has revolutionized the way my team plans corporate retreats. With its personalized trip planning assistance and extensive destination guides, we''ve been able to organize successful events with ease.', 'https://i.ibb.co/Yb0xxJs/John.jpg', GETUTCDATE(), GETUTCDATE());
    INSERT INTO [MTE].[Testimonial] ([ClientName], [ClientProfession], [Review], [ClientPhotoUrl], [CreatedDate], [ModifiedDate]) VALUES ('Sophia Grace', 'Adventure Seeker', 'I can''t thank Mini Traveling Explorer enough for helping me discover hidden gems and plan thrilling adventures. From adrenaline-pumping activities to cozy accommodations, this platform has everything I need for unforgettable experiences.', 'https://i.ibb.co/pzjYq4p/Sophia.jpg', GETUTCDATE(), GETUTCDATE());
    INSERT INTO [MTE].[Testimonial] ([ClientName], [ClientProfession], [Review], [ClientPhotoUrl], [CreatedDate], [ModifiedDate]) VALUES ('David Johnson', 'Travel Organizer', 'Mini Traveling Explorer''s daily checklist feature has transformed the way I plan my trips. With its organized and customizable lists, I can efficiently manage every aspect of my journey, ensuring nothing is overlooked. This tool has become an essential part of my travel routine, allowing me to stay organized and focused on enjoying every moment of my adventures.', 'https://i.ibb.co/C2BwLkj/David.jpg', GETUTCDATE(), GETUTCDATE());
END