IF (EXISTS (SELECT * 
                 FROM [INFORMATION_SCHEMA].[TABLES] 
                 WHERE [TABLE_SCHEMA] = 'MTE'
				 AND [TABLE_NAME] = 'Room'))
BEGIN
    INSERT INTO [MTE].[Room] ([Name], [Rating], [Rate], [CurrencyId], [PerDayOrNight], [BedNumber], [BathNumber], [HasWifi], [Description], [IsFeatured], [RoomImageUrl], [CreatedDate], [ModifiedDate]) VALUES ('Cozy Studio Apartment', 4, 100, 1, 'Night', 1, 1, 1, 'A comfortable studio apartment with a scenic view', 1, 'https://i.imghippo.com/files/9KevD1723238090.jpg', GETUTCDATE(), GETUTCDATE());
    INSERT INTO [MTE].[Room] ([Name], [Rating], [Rate], [CurrencyId], [PerDayOrNight], [BedNumber], [BathNumber], [HasWifi], [Description], [IsFeatured], [RoomImageUrl], [CreatedDate], [ModifiedDate]) VALUES ('Luxury Suite', 5, 150, 1, 'Night', 1, 1, 1, 'A luxurious suite overlooking the ocean', 1, 'https://i.imghippo.com/files/NkADD1723240550.jpg', GETUTCDATE(), GETUTCDATE());
    INSERT INTO [MTE].[Room] ([Name], [Rating], [Rate], [CurrencyId], [PerDayOrNight], [BedNumber], [BathNumber], [HasWifi], [Description], [IsFeatured], [RoomImageUrl], [CreatedDate], [ModifiedDate]) VALUES ('Rustic Cabin Retreat', 3.5, 200, 1, 'Night', 1, 1, 1, 'A cozy cabin nestled in the woods', 1, 'https://i.imghippo.com/files/aX7m01723240631.jpg', GETUTCDATE(), GETUTCDATE());
    INSERT INTO [MTE].[Room] ([Name], [Rating], [Rate], [CurrencyId], [PerDayOrNight], [BedNumber], [BathNumber], [HasWifi], [Description], [IsFeatured], [RoomImageUrl], [CreatedDate], [ModifiedDate]) VALUES ('Charming Cottage', 4, 180, 1, 'Night', 2, 1, 1, 'A charming cottage with a garden view', 0,  'https://i.imghippo.com/files/qxUMj1723240391.jpg', GETUTCDATE(), GETUTCDATE());
    INSERT INTO [MTE].[Room] ([Name], [Rating], [Rate], [CurrencyId], [PerDayOrNight], [BedNumber], [BathNumber], [HasWifi], [Description], [IsFeatured], [RoomImageUrl], [CreatedDate], [ModifiedDate]) VALUES ('Executive Business Room', 4, 80, 1, 'Night', 1, 1, 1, 'An executive room designed for business travelers', 0,  'https://i.imghippo.com/files/xIE2t1723240462.jpg', GETUTCDATE(), GETUTCDATE());
    INSERT INTO [MTE].[Room] ([Name], [Rating], [Rate], [CurrencyId], [PerDayOrNight], [BedNumber], [BathNumber], [HasWifi], [Description], [IsFeatured], [RoomImageUrl], [CreatedDate], [ModifiedDate]) VALUES ('Family-Friendly Apartment', 4.5, 120, 1, 'Night', 2, 1, 1, 'A spacious apartment suitable for families', 0,  'https://i.imghippo.com/files/V08zm1723240502.jpg', GETUTCDATE(), GETUTCDATE());
    INSERT INTO [MTE].[Room] ([Name], [Rating], [Rate], [CurrencyId], [PerDayOrNight], [BedNumber], [BathNumber], [HasWifi], [Description], [IsFeatured], [RoomImageUrl], [CreatedDate], [ModifiedDate]) VALUES ('Mountain View Chalet', 5, 250, 1, 'Night', 1, 1, 1, 'A cozy chalet with stunning mountain views', 0,  'https://i.imghippo.com/files/tofne1723240605.jpg', GETUTCDATE(), GETUTCDATE());
    INSERT INTO [MTE].[Room] ([Name], [Rating], [Rate], [CurrencyId], [PerDayOrNight], [BedNumber], [BathNumber], [HasWifi], [Description], [IsFeatured], [RoomImageUrl], [CreatedDate], [ModifiedDate]) VALUES ('Beachfront Bungalow', 5, 300, 1, 'Night', 1, 1, 1, 'A luxurious bungalow steps away from the beach', 0,  'https://i.imghippo.com/files/FLD5S1723240324.jpg', GETUTCDATE(), GETUTCDATE());
    INSERT INTO [MTE].[Room] ([Name], [Rating], [Rate], [CurrencyId], [PerDayOrNight], [BedNumber], [BathNumber], [HasWifi], [Description], [IsFeatured], [RoomImageUrl], [CreatedDate], [ModifiedDate]) VALUES ('Historic Inn Room', 3, 400, 1, 'Night', 1, 1, 1, 'A room in a historic inn with period charm', 0,  'https://i.imghippo.com/files/rrIgc1723240528.jpg', GETUTCDATE(), GETUTCDATE());
    INSERT INTO [MTE].[Room] ([Name], [Rating], [Rate], [CurrencyId], [PerDayOrNight], [BedNumber], [BathNumber], [HasWifi], [Description], [IsFeatured], [RoomImageUrl], [CreatedDate], [ModifiedDate]) VALUES ('Budget-Friendly Hostel Dorm', 2, 500, 1, 'Night', 25, 2, 0, 'A budget-friendly option for solo travelers', 0,  'https://i.imghippo.com/files/qu6J51723240370.jpg', GETUTCDATE(), GETUTCDATE());
END